# Generated by Django 2.2.5 on 2019-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
    ]
