# Generated by Django 2.2.5 on 2019-11-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191019_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_plural',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок во мн. числе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок в ед. числе'),
        ),
    ]
